# Generated by Django 5.2.17 on 2026-08-05 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PathMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_prefix', models.CharField(help_text='Path as the *arr sees it.', max_length=500)),
                ('target_prefix', models.CharField(help_text='Path as Plex sees it.', max_length=500)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Lower is applied first.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('request_manager', 'Request manager'), ('sonarr', 'Sonarr'), ('radarr', 'Radarr'), ('download_client', 'Download client'), ('plex', 'Plex')], max_length=32)),
                ('variant', models.CharField(choices=[('seerr', 'Seerr'), ('overseerr', 'Overseerr'), ('jellyseerr', 'Jellyseerr'), ('qbittorrent', 'qBittorrent'), ('native', 'Native')], default='native', max_length=32)),
                ('name', models.CharField(help_text='Label shown in the UI.', max_length=100)),
                ('base_url', models.CharField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('verify_tls', models.BooleanField(default=True)),
                ('poll_interval', models.PositiveIntegerField(default=60, help_text='Seconds.')),
                ('remote_service_id', models.IntegerField(blank=True, help_text="The request manager's serviceId for this Sonarr/Radarr instance.", null=True)),
                ('is_4k', models.BooleanField(default=False, help_text="This instance handles the request manager's 4K lane.")),
                ('last_seen_ok', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('backoff_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(help_text='MediaRequest.id upstream.')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=16)),
                ('requested_by', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField()),
                ('updated_at_remote', models.DateTimeField(blank=True, null=True)),
                ('request_state', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('failed', 'Failed'), ('completed', 'Completed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('availability', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('processing', 'Processing'), ('partial', 'Partially available'), ('available', 'Available'), ('blocklisted', 'Blocklisted'), ('deleted', 'Deleted')], default='unknown', max_length=16)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('tvdb_id', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=32)),
                ('is_4k', models.BooleanField(default=False)),
                ('requested_seasons', models.JSONField(blank=True, default=list)),
                ('arr_entity_id', models.IntegerField(blank=True, null=True)),
                ('arr_title_slug', models.CharField(blank=True, max_length=255)),
                ('arr_monitored', models.BooleanField(blank=True, null=True)),
                ('arr_has_file', models.BooleanField(blank=True, null=True)),
                ('arr_quality_profile_id', models.IntegerField(blank=True, null=True)),
                ('arr_quality_profile_name', models.CharField(blank=True, max_length=128)),
                ('arr_snapshot', models.JSONField(blank=True, default=dict)),
                ('arr_last_synced', models.DateTimeField(blank=True, null=True)),
                ('plex_rating_key', models.CharField(blank=True, max_length=64)),
                ('plex_found', models.BooleanField(blank=True, null=True)),
                ('plex_matched_path', models.CharField(blank=True, max_length=1000)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('arr_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_requests', to='core.serviceinstance')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.serviceinstance')),
            ],
            options={
                'ordering': ['requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('request_manager', 'Request manager'), ('sonarr', 'Sonarr'), ('radarr', 'Radarr'), ('download_client', 'Download client'), ('plex', 'Plex')], max_length=32)),
                ('event_type', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('request_failed', 'Request failed'), ('added_to_arr', 'Added to library'), ('not_in_arr', 'Not found in library'), ('grabbed', 'Grabbed'), ('download_failed', 'Download failed'), ('download_ignored', 'Download ignored'), ('imported', 'Imported'), ('file_deleted', 'File deleted'), ('file_renamed', 'File renamed'), ('queued', 'In download queue'), ('download_progress', 'Download progress'), ('import_blocked', 'Import blocked'), ('plex_available', 'Available in Plex'), ('plex_missing', 'Not found in Plex'), ('unknown', 'Unknown')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceinstance')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.trackedrequest')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('ok', 'OK'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('message', models.TextField()),
                ('next_step', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=1000)),
                ('link_label', models.CharField(blank=True, max_length=120)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.ManyToManyField(blank=True, related_name='cited_by', to='core.timelineevent')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='core.trackedrequest')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='IngestCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text="e.g. 'requests', or 'history:movie:412'.", max_length=120)),
                ('high_water', models.DateTimeField(blank=True, null=True)),
                ('last_page', models.IntegerField(default=0)),
                ('backfill_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to='core.serviceinstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'scope'), name='uniq_cursor_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='trackedrequest',
            index=models.Index(fields=['media_type', 'request_state'], name='core_tracke_media_t_d53aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedrequest',
            index=models.Index(fields=['tmdb_id'], name='core_tracke_tmdb_id_5a2f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedrequest',
            index=models.Index(fields=['tvdb_id'], name='core_tracke_tvdb_id_9ea86f_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackedrequest',
            constraint=models.UniqueConstraint(fields=('service', 'remote_id'), name='uniq_request_per_service'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['request', 'occurred_at'], name='core_timeli_request_798e2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.UniqueConstraint(fields=('request', 'dedupe_key'), name='uniq_event_per_request'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['code'], name='core_diagno_code_44b00a_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['severity'], name='core_diagno_severit_ff6006_idx'),
        ),
    ]
