# Generated by Django 5.2.17 on 2026-08-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cutoff_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestcursor',
            name='last_reconcile',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
