# Generated by Django 5.2.17 on 2026-08-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_last_reconcile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='facts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
