# Generated by Django 5.2.17 on 2026-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_event_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='client_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
